# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InControl.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from datetime import datetime
import logo
import InEstudiante
from Metodos import*

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(723, 559)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.522, y1:0.516909, x2:0.517, y2:1, stop:0.448864 rgba(65, 63, 205, 37), stop:1 rgba(255, 255, 255, 255));")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setStyleSheet("font: 87 18pt \"Arial Black\";\n"
"color: rgb(0,0,0);\n"
"background-color: rgba(0, 0, 0,0%);\n"
"\n"
"\n"
"")
        self.label.setObjectName("label")
        self.horizontalLayout_5.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setStyleSheet("\n"
"font: 87 11pt \"Arial Black\";\n"
"color: rgb(0,0,0);\n"
"background-color: rgba(0, 0, 0,0%);")
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 0, 1, 1)
        self.ContTempe = QtWidgets.QLineEdit(self.frame)
        self.ContTempe.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 87 11pt \"Arial\";\n"
"border-bottom: 1px solid black;")
        self.ContTempe.setObjectName("ContTempe")
        self.gridLayout.addWidget(self.ContTempe, 8, 1, 1, 1)
        self.HisNombre = QtWidgets.QLabel(self.frame)
        self.HisNombre.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 87 11pt \"Arial\";\n"
"border-bottom: 1px solid black;")
        self.HisNombre.setText("")
        self.HisNombre.setObjectName("HisNombre")
        self.gridLayout.addWidget(self.HisNombre, 3, 1, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.frame)
        self.label_10.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 87 11pt \"Arial \";\n"
"color: rgb(0,0,0);")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 3, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.frame)
        self.label_11.setStyleSheet("\n"
"background-color: rgba(0, 0, 0,0%);\n"
"font: 87 11pt \"Arial \";\n"
"color: rgb(0,0,0);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.frame)
        self.label_9.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 87 11pt \"Arial \";\n"
"color: rgb(0,0,0);")
        self.label_9.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setStyleSheet("\n"
"font: 87 11pt \"Arial\";\n"
"color: rgb(0,0,0);\n"
"background-color: rgba(0, 0, 0,0%);")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 8, 0, 1, 1)
        self.HisFechaNac = QtWidgets.QLabel(self.frame)
        self.HisFechaNac.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 87 11pt \"Arial\";\n"
"border-bottom: 1px solid black;")
        self.HisFechaNac.setText("")
        self.HisFechaNac.setObjectName("HisFechaNac")
        self.gridLayout.addWidget(self.HisFechaNac, 5, 1, 1, 1)
        self.HisApellido = QtWidgets.QLabel(self.frame)
        self.HisApellido.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 87 11pt \"Arial\";\n"
"border-bottom: 1px solid black;\n"
"")
        self.HisApellido.setText("")
        self.HisApellido.setObjectName("HisApellido")
        self.gridLayout.addWidget(self.HisApellido, 4, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 87 11pt \"Arial \";\n"
"color: rgb(0,0,0);")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 5, 0, 1, 1)
        self.HisNumHis = QtWidgets.QLabel(self.frame)
        self.HisNumHis.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 87 11pt \"Arial\";\n"
"border-bottom: 1px solid black;")
        self.HisNumHis.setText("")
        self.HisNumHis.setObjectName("HisNumHis")
        self.gridLayout.addWidget(self.HisNumHis, 1, 1, 1, 1)
        self.HisIdenti = QtWidgets.QLabel(self.frame)
        self.HisIdenti.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 87 11pt \"Arial\";\n"
"border-bottom: 1px solid black;\n"
"")
        self.HisIdenti.setText("")
        self.HisIdenti.setObjectName("HisIdenti")
        self.gridLayout.addWidget(self.HisIdenti, 2, 1, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setStyleSheet("font: 87 11pt \"Arial \";\n"
"color: rgb(0,0,0);\n"
"background-color: rgba(0, 0, 0,0%);")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 1, 0, 1, 1)
        self.ContHora = QtWidgets.QLineEdit(self.frame)
        self.ContHora.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 87 11pt \"Arial\";\n"
"border-bottom: 1px solid black;")
        self.ContHora.setObjectName("ContHora")
        self.gridLayout.addWidget(self.ContHora, 10, 1, 1, 1)
        self.ContComJorn = QtWidgets.QComboBox(self.frame)
        self.ContComJorn.setMinimumSize(QtCore.QSize(174, 21))
        self.ContComJorn.setStyleSheet("background-color: rgb(214, 214, 235);\n"
"border: none;\n"
"font: 87 11pt \"Arial\";\n"
"border-bottom: 1px solid black;\n"
"")
        self.ContComJorn.setObjectName("ContComJorn")
        self.ContComJorn.addItem("")
        self.ContComJorn.addItem("")
        self.gridLayout.addWidget(self.ContComJorn, 9, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setStyleSheet("\n"
"font: 87 11pt \"Arial \";\n"
"color: rgb(0,0,0);\n"
"background-color: rgba(0, 0, 0,0%);")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 9, 0, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.frame)
        self.label_13.setStyleSheet("\n"
"font: 87 11pt \"Arial Black\";\n"
"color: rgb(0,0,0);\n"
"background-color: rgba(0, 0, 0,0%);")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 7, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setStyleSheet("\n"
"font: 87 11pt \"Arial\";\n"
"color: rgb(0,0,0);\n"
"background-color: rgba(0, 0, 0,0%);")
        self.label_12.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 11, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setStyleSheet("\n"
"font: 87 11pt \"Arial \";\n"
"color: rgb(0,0,0);\n"
"background-color: rgba(0, 0, 0,0%);")
        self.label_3.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 10, 0, 1, 1)
        self.ContFecha = QtWidgets.QLineEdit(self.frame)
        self.ContFecha.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 87 11pt \"Arial\";\n"
"border-bottom: 1px solid black;")
        self.ContFecha.setObjectName("ContFecha")
        self.gridLayout.addWidget(self.ContFecha, 11, 1, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem4, 6, 0, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.ContBotGuardar = QtWidgets.QPushButton(self.frame)
        self.ContBotGuardar.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.ContBotGuardar.setObjectName("ContBotGuardar")
        self.verticalLayout.addWidget(self.ContBotGuardar)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem6)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem7)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem8)
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setMinimumSize(QtCore.QSize(120, 120))
        self.label_2.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.ContBotRegresar_2 = QtWidgets.QPushButton(self.frame)
        self.ContBotRegresar_2.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.ContBotRegresar_2.setObjectName("ContBotRegresar_2")
        self.verticalLayout_3.addWidget(self.ContBotRegresar_2)
        spacerItem9 = QtWidgets.QSpacerItem(20, 28, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem9)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem10)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem11)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem12)
        self.ContBotRegresar = QtWidgets.QPushButton(self.frame)
        self.ContBotRegresar.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.ContBotRegresar.setObjectName("ContBotRegresar")
        self.horizontalLayout.addWidget(self.ContBotRegresar)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        datetime.now()
        fecha = datetime.now().strftime('%d-%m-%Y')
        hour = datetime.now().strftime('%H:%M:%S')

        self.ContFecha.setText(fecha)
        self.ContHora.setText(hour)
        self.varid = ''  # variable que guarda el id
        self.datoTotal = Metodos()
        self.ContBotGuardar.clicked.connect(self.registrarControl)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Control estudiante"))
        self.label_6.setText(_translate("MainWindow", "Datos personales"))
        self.label_10.setText(_translate("MainWindow", "Nombres:"))
        self.label_11.setText(_translate("MainWindow", "Apellidos:"))
        self.label_9.setText(_translate("MainWindow", "Identificación:"))
        self.label_5.setText(_translate("MainWindow", "Temperatura:"))
        self.label_8.setText(_translate("MainWindow", "Fecha de nacimiento:"))
        self.label_7.setText(_translate("MainWindow", "Numero de historia:"))
        self.ContComJorn.setItemText(0, _translate("MainWindow", "Diurna"))
        self.ContComJorn.setItemText(1, _translate("MainWindow", "Nocturna"))
        self.label_4.setText(_translate("MainWindow", "Jornada:"))
        self.label_13.setText(_translate("MainWindow", "Datos Control"))
        self.label_12.setText(_translate("MainWindow", "Fecha:"))
        self.label_3.setText(_translate("MainWindow", "Hora:"))
        self.ContBotGuardar.setText(_translate("MainWindow", "Guardar"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (27).png\"/></p></body></html>"))
        self.ContBotRegresar_2.setText(_translate("MainWindow", "Encuesta"))
        self.ContBotRegresar.setText(_translate("MainWindow", "Regresar"))
    def registrarControl(self):
        if not self.ContTempe.text() or not self.ContHora.text() or not self.ContFecha.text():
            confirmar = QtWidgets.QMessageBox()
            confirmar.setIcon(confirmar.Warning)
            confirmar.setText("¡Hay campos vacíos!")
            confirmar.exec_()
        else:
            temp=self.ContTempe.text()
            hor=self.ContHora.text()
            fec=self.ContFecha.text()
            jor=self.ContComJorn.currentText()
            idEst=self.varid
            idCont='sa'
            idEncue='Paa'
            self.datoTotal.AgregrarControl(idCont,jor,hor,fec,temp,idEst,idEncue)
            confirmar = QtWidgets.QMessageBox()
            confirmar.setIcon(confirmar.Warning)
            confirmar.setText("¡Se ha registrado con éxito!")
            confirmar.exec_()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
