# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InGestionarEstudiante.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


import sys
from Metodos import*
import logo
import InIngreso2
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindowGestionar(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(829, 640)
        MainWindow.setMinimumSize(QtCore.QSize(550, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        MainWindow.setStyleSheet( "background-color: qlineargradient(spread:pad, x1:0.522, y1:0.516909, x2:0.517, y2:1, stop:0.448864 rgba(65, 63, 205, 75), stop:1 rgba(255, 255, 255, 255));\n"
                "")

        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.frame)
        self.tabWidget.setStyleSheet("QTabWidget::pane{\n"
"            \n"
"            border-width: 2px;\n"
"            border-style: solid;\n"
"            border-color:#000000;\n"
"            border-radius: 5px;\n"
"\n"
"        }\n"
"\n"
"QTabBar::tab:hover{\n"
"            background-color: #00aaff;\n"
"            border: 1px solid #000000;\n"
"\n"
"        }\n"
"\n"
"QTabBar::tab{\n"
"            background-color: #d4bff5;\n"
"            border: 2px solid #000000;\n"
"            width:100px;\n"
"            border-radius: 2px;\n"
"            border-top-left-radius:5px;\n"
"            border-top-rigth-radius:5px;\n"
"            padding:6px 0px;\n"
"        }")
        self.tabWidget.setIconSize(QtCore.QSize(64, 64))
        self.tabWidget.setMovable(True)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tab)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setStyleSheet("font: 87 18pt \"Arial Black\";\n"
"color: rgb(0,0,0);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_4.addLayout(self.horizontalLayout)
        self.TablaEstudiante = QtWidgets.QTableWidget(self.tab)
        self.TablaEstudiante.setStyleSheet("QWidget{\n"
"        background-color:#ffffff;\n"
"        color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"        background-color:#55aaff;\n"
"        padding:2px;\n"
"        border:1px solid #fffff8;\n"
"        font-size:12pt;\n"
"        \n"
"}\n"
"QTableWidget{\n"
"        gridline-color: #000000;\n"
"        font-size:12pt;\n"
"}\n"
"QTableWidget QTableCornerButton:section{\n"
"        background-color:#55aaff;\n"
"        border:1px solid #ffffff;\n"
"}\n"
"\n"
"")
        self.TablaEstudiante.setObjectName("TablaEstudiante")
        self.TablaEstudiante.setColumnCount(7)
        self.TablaEstudiante.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEstudiante.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEstudiante.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEstudiante.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEstudiante.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEstudiante.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEstudiante.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEstudiante.setHorizontalHeaderItem(6, item)
        self.verticalLayout_4.addWidget(self.TablaEstudiante)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.RegresarBase = QtWidgets.QPushButton(self.tab)
        self.RegresarBase.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.RegresarBase.setObjectName("RegresarBase")
        self.horizontalLayout_7.addWidget(self.RegresarBase)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_7)
        self.Refrescar = QtWidgets.QPushButton(self.tab)
        self.Refrescar.setStyleSheet("\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.Refrescar.setObjectName("Refrescar")
        self.horizontalLayout_8.addWidget(self.Refrescar)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/cct/imagenes/klipartz.com (14).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab, icon, "")
        self.widget = QtWidgets.QWidget()
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setStyleSheet("font: 87 18pt \"Arial Black\";\n"
"color: rgb(0,0,0);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.TablaInsertar = QtWidgets.QTableWidget(self.widget)
        self.TablaInsertar.setStyleSheet("QWidget{\n"
"        background-color:#ffffff;\n"
"        color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"        background-color:#55aaff;\n"
"        padding:2px;\n"
"        border:1px solid #fffff8;\n"
"        font-size:12pt;\n"
"        \n"
"}\n"
"QTableWidget{\n"
"        gridline-color: #000000;\n"
"        font-size:12pt;\n"
"}\n"
"QTableWidget QTableCornerButton:section{\n"
"        background-color:#55aaff;\n"
"        border:1px solid #ffffff;\n"
"}\n"
"\n"
"")
        self.TablaInsertar.setObjectName("TablaInsertar")
        self.TablaInsertar.setColumnCount(7)
        self.TablaInsertar.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablaInsertar.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaInsertar.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaInsertar.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaInsertar.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaInsertar.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaInsertar.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaInsertar.setHorizontalHeaderItem(6, item)
        self.verticalLayout.addWidget(self.TablaInsertar)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_3.addWidget(self.label_6)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem5)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setMinimumSize(QtCore.QSize(30, 25))
        self.label_7.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 0, 1, 1)
        self.ReNombres = QtWidgets.QLineEdit(self.widget)
        self.ReNombres.setMinimumSize(QtCore.QSize(174, 25))
        self.ReNombres.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 12pt \"Arial\";\n"
"border: none;\n"
"\n"
"border-bottom: 1px solid black;")
        self.ReNombres.setObjectName("ReNombres")
        self.gridLayout.addWidget(self.ReNombres, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 2, 1, 1)
        self.ReApellidos = QtWidgets.QLineEdit(self.widget)
        self.ReApellidos.setMinimumSize(QtCore.QSize(174, 21))
        self.ReApellidos.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 12pt \"Arial\";\n"
"border-bottom: 1px solid black;")
        self.ReApellidos.setObjectName("ReApellidos")
        self.gridLayout.addWidget(self.ReApellidos, 0, 3, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setMinimumSize(QtCore.QSize(30, 25))
        self.label_10.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.Reidd = QtWidgets.QLineEdit(self.widget)
        self.Reidd.setMinimumSize(QtCore.QSize(174, 25))
        self.Reidd.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 12pt \"Segoe MDL2 Assets\";\n"
"border-bottom: 1px solid black;")
        self.Reidd.setObjectName("Reidd")
        self.gridLayout.addWidget(self.Reidd, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 1, 2, 1, 1)
        self.ReComboSex = QtWidgets.QComboBox(self.widget)
        self.ReComboSex.setMinimumSize(QtCore.QSize(174, 21))
        self.ReComboSex.setStyleSheet("\n"
"border: none;\n"
"font: 12pt \"Arial\";\n"
"border-bottom: 1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.ReComboSex.setObjectName("ReComboSex")
        self.ReComboSex.addItem("")
        self.ReComboSex.addItem("")
        self.ReComboSex.addItem("")
        self.gridLayout.addWidget(self.ReComboSex, 1, 3, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setMinimumSize(QtCore.QSize(30, 25))
        self.label_12.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.ReComboTipo = QtWidgets.QComboBox(self.widget)
        self.ReComboTipo.setMinimumSize(QtCore.QSize(174, 25))
        self.ReComboTipo.setStyleSheet("\n"
"border: none;\n"
"font:12pt \"Arial\";\n"
"border-bottom: 1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.ReComboTipo.setObjectName("ReComboTipo")
        self.ReComboTipo.addItem("")
        self.ReComboTipo.addItem("")
        self.ReComboTipo.addItem("")
        self.gridLayout.addWidget(self.ReComboTipo, 2, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 2, 2, 1, 1)
        self.ReNiden = QtWidgets.QLineEdit(self.widget)
        self.ReNiden.setMinimumSize(QtCore.QSize(174, 21))
        self.ReNiden.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"font: 12pt \"Arial\";\n"
"border-bottom: 1px solid black;")
        self.ReNiden.setObjectName("ReNiden")
        self.gridLayout.addWidget(self.ReNiden, 2, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 3, 2, 1, 1)
        self.ReFecNac = QtWidgets.QLineEdit(self.widget)
        self.ReFecNac.setMinimumSize(QtCore.QSize(174, 21))
        self.ReFecNac.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 12pt \"Segoe MDL2 Assets\";\n"
"border-bottom: 1px solid black;")
        self.ReFecNac.setObjectName("ReFecNac")
        self.gridLayout.addWidget(self.ReFecNac, 3, 3, 1, 1)
        self.horizontalLayout_5.addLayout(self.gridLayout)
        self.ReCalen = QtWidgets.QCalendarWidget(self.widget)
        self.ReCalen.setStyleSheet("background-color: rgb(221, 225, 255);\n"
"color: rgb(0, 0, 0);\n"
"\n"
"\n"
"")
        self.ReCalen.setObjectName("ReCalen")
        self.horizontalLayout_5.addWidget(self.ReCalen)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ReRegresar = QtWidgets.QPushButton(self.widget)
        self.ReRegresar.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.ReRegresar.setObjectName("ReRegresar")
        self.horizontalLayout_4.addWidget(self.ReRegresar)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem6)
        self.Registrar = QtWidgets.QPushButton(self.widget)
        self.Registrar.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.Registrar.setObjectName("Registrar")
        self.horizontalLayout_4.addWidget(self.Registrar)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/cct/imagenes/klipartz.com (15).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.widget, icon1, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem7)
        self.label_3 = QtWidgets.QLabel(self.tab_4)
        self.label_3.setStyleSheet("font: 87 18pt \"Arial Black\";\n"
"color: rgb(0,0,0);")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem8)
        self.verticalLayout_7.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem9)
        self.label_22 = QtWidgets.QLabel(self.tab_4)
        self.label_22.setMinimumSize(QtCore.QSize(169, 30))
        self.label_22.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 87 11pt \"Arial Black\";\n"
"")
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_14.addWidget(self.label_22)
        self.EliComboConsu = QtWidgets.QComboBox(self.tab_4)
        self.EliComboConsu.setMinimumSize(QtCore.QSize(165, 21))
        self.EliComboConsu.setStyleSheet("\n"
"border: none;\n"
"font:12pt \"Arial\";\n"
"border-bottom: 1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.EliComboConsu.setObjectName("EliComboConsu")
        self.EliComboConsu.addItem("")
        self.EliComboConsu.addItem("")
        self.EliComboConsu.addItem("")
        self.EliComboConsu.addItem("")
        self.EliComboConsu.addItem("")
        self.horizontalLayout_14.addWidget(self.EliComboConsu)
        self.EliConTex = QtWidgets.QLineEdit(self.tab_4)
        self.EliConTex.setMinimumSize(QtCore.QSize(165, 21))
        self.EliConTex.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 12pt \"Arial\";\n"
"border: none;\n"
"\n"
"border-bottom: 1px solid black;")
        self.EliConTex.setObjectName("EliConTex")
        self.horizontalLayout_14.addWidget(self.EliConTex)
        self.horizontalLayout_15.addLayout(self.horizontalLayout_14)
        self.EliBotonConsu = QtWidgets.QPushButton(self.tab_4)
        self.EliBotonConsu.setMinimumSize(QtCore.QSize(97, 32))
        self.EliBotonConsu.setStyleSheet("\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.EliBotonConsu.setObjectName("EliBotonConsu")
        self.horizontalLayout_15.addWidget(self.EliBotonConsu)
        self.verticalLayout_7.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_16.addItem(spacerItem10)
        self.label_23 = QtWidgets.QLabel(self.tab_4)
        self.label_23.setMinimumSize(QtCore.QSize(169, 30))
        self.label_23.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 87 11pt \"Arial Black\";\n"
"")
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_16.addWidget(self.label_23)
        self.EliCombo = QtWidgets.QComboBox(self.tab_4)
        self.EliCombo.setMinimumSize(QtCore.QSize(165, 21))
        self.EliCombo.setStyleSheet("\n"
"border: none;\n"
"font:12pt \"Arial\";\n"
"border-bottom: 1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.EliCombo.setObjectName("EliCombo")
        self.EliCombo.addItem("")
        self.EliCombo.addItem("")
        self.EliCombo.addItem("")
        self.EliCombo.addItem("")
        self.EliCombo.addItem("")
        self.horizontalLayout_16.addWidget(self.EliCombo)
        self.EliTex = QtWidgets.QLineEdit(self.tab_4)
        self.EliTex.setMinimumSize(QtCore.QSize(165, 21))
        self.EliTex.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 12pt \"Arial\";\n"
"border: none;\n"
"\n"
"border-bottom: 1px solid black;")
        self.EliTex.setObjectName("EliTex")
        self.horizontalLayout_16.addWidget(self.EliTex)
        self.EliBoton = QtWidgets.QPushButton(self.tab_4)
        self.EliBoton.setMinimumSize(QtCore.QSize(97, 32))
        self.EliBoton.setStyleSheet("\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.EliBoton.setObjectName("EliBoton")
        self.horizontalLayout_16.addWidget(self.EliBoton)
        self.verticalLayout_7.addLayout(self.horizontalLayout_16)
        self.TablaEli = QtWidgets.QTableWidget(self.tab_4)
        self.TablaEli.setStyleSheet("QWidget{\n"
"        background-color:#ffffff;\n"
"        color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"        background-color:#55aaff;\n"
"        padding:2px;\n"
"        border:1px solid #fffff8;\n"
"        font-size:12pt;\n"
"        \n"
"}\n"
"QTableWidget{\n"
"        gridline-color: #000000;\n"
"        font-size:12pt;\n"
"}\n"
"QTableWidget QTableCornerButton:section{\n"
"        background-color:#55aaff;\n"
"        border:1px solid #ffffff;\n"
"}\n"
"\n"
"")
        self.TablaEli.setObjectName("TablaEli")
        self.TablaEli.setColumnCount(7)
        self.TablaEli.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEli.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEli.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEli.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEli.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEli.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEli.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaEli.setHorizontalHeaderItem(6, item)
        self.verticalLayout_7.addWidget(self.TablaEli)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.EliBotonRegre = QtWidgets.QPushButton(self.tab_4)
        self.EliBotonRegre.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.EliBotonRegre.setObjectName("EliBotonRegre")
        self.horizontalLayout_17.addWidget(self.EliBotonRegre)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/cct/imagenes/klipartz.com (17).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon2, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem12)
        self.label_4 = QtWidgets.QLabel(self.tab_5)
        self.label_4.setStyleSheet("font: 87 18pt \"Arial Black\";\n"
"color: rgb(0,0,0);")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_9.addWidget(self.label_4)
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem13)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem14)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.label_21 = QtWidgets.QLabel(self.tab_5)
        self.label_21.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 87 11pt \"Arial Black\";\n"
"")
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_13.addWidget(self.label_21)
        self.ConCombo = QtWidgets.QComboBox(self.tab_5)
        self.ConCombo.setMinimumSize(QtCore.QSize(165, 21))
        self.ConCombo.setStyleSheet("\n"
"border: none;\n"
"font:12pt \"Arial\";\n"
"border-bottom: 1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.ConCombo.setObjectName("ConCombo")
        self.ConCombo.addItem("")
        self.ConCombo.addItem("")
        self.ConCombo.addItem("")
        self.ConCombo.addItem("")
        self.ConCombo.addItem("")
        self.horizontalLayout_13.addWidget(self.ConCombo)
        self.ConTex = QtWidgets.QLineEdit(self.tab_5)
        self.ConTex.setMinimumSize(QtCore.QSize(165, 21))
        self.ConTex.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 12pt \"Arial\";\n"
"border: none;\n"
"\n"
"border-bottom: 1px solid black;")
        self.ConTex.setObjectName("ConTex")
        self.horizontalLayout_13.addWidget(self.ConTex)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_13)
        self.ConBoton = QtWidgets.QPushButton(self.tab_5)
        self.ConBoton.setStyleSheet("\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.ConBoton.setObjectName("ConBoton")
        self.horizontalLayout_19.addWidget(self.ConBoton)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_19)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.TablaCon = QtWidgets.QTableWidget(self.tab_5)
        self.TablaCon.setStyleSheet("QWidget{\n"
"        background-color:#ffffff;\n"
"        color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"        background-color:#55aaff;\n"
"        padding:2px;\n"
"        border:1px solid #fffff8;\n"
"        font-size:12pt;\n"
"        \n"
"}\n"
"QTableWidget{\n"
"        gridline-color: #000000;\n"
"        font-size:12pt;\n"
"}\n"
"QTableWidget QTableCornerButton:section{\n"
"        background-color:#55aaff;\n"
"        border:1px solid #ffffff;\n"
"}\n"
"\n"
"")
        self.TablaCon.setObjectName("TablaCon")
        self.TablaCon.setColumnCount(7)
        self.TablaCon.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablaCon.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaCon.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaCon.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaCon.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaCon.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaCon.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaCon.setHorizontalHeaderItem(6, item)
        self.verticalLayout_6.addWidget(self.TablaCon)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.ConRegresar = QtWidgets.QPushButton(self.tab_5)
        self.ConRegresar.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.ConRegresar.setObjectName("ConRegresar")
        self.horizontalLayout_18.addWidget(self.ConRegresar)
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_18.addItem(spacerItem15)
        self.verticalLayout_6.addLayout(self.horizontalLayout_18)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/cct/imagenes/klipartz.com (19).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon3, "")
        self.widget1 = QtWidgets.QWidget()
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem16)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setStyleSheet("font: 87 18pt \"Arial Black\";\n"
"color: rgb(0,0,0);")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_10.addWidget(self.label_5)
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem17)
        self.verticalLayout_2.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem18)
        self.label_14 = QtWidgets.QLabel(self.widget1)
        self.label_14.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 87 11pt \"Arial Black\";\n"
"")
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_12.addWidget(self.label_14)
        self.ActCombo = QtWidgets.QComboBox(self.widget1)
        self.ActCombo.setMinimumSize(QtCore.QSize(165, 21))
        self.ActCombo.setStyleSheet("\n"
"border: none;\n"
"font:12pt \"Arial\";\n"
"border-bottom: 1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.ActCombo.setObjectName("ActCombo")
        self.ActCombo.addItem("")
        self.ActCombo.addItem("")
        self.ActCombo.addItem("")
        self.ActCombo.addItem("")
        self.ActCombo.addItem("")
        self.horizontalLayout_12.addWidget(self.ActCombo)
        self.ActTex = QtWidgets.QLineEdit(self.widget1)
        self.ActTex.setMinimumSize(QtCore.QSize(165, 21))
        self.ActTex.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 12pt \"Arial\";\n"
"border: none;\n"
"\n"
"border-bottom: 1px solid black;")
        self.ActTex.setObjectName("ActTex")
        self.horizontalLayout_12.addWidget(self.ActTex)
        self.ActBotonFiltrar = QtWidgets.QPushButton(self.widget1)
        self.ActBotonFiltrar.setStyleSheet("\n"
"QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.ActBotonFiltrar.setObjectName("ActBotonFiltrar")
        self.horizontalLayout_12.addWidget(self.ActBotonFiltrar)
        self.verticalLayout_2.addLayout(self.horizontalLayout_12)
        self.TablaAct = QtWidgets.QTableWidget(self.widget1)
        self.TablaAct.setStyleSheet("QWidget{\n"
"        background-color:#ffffff;\n"
"        color:#000000;\n"
"}\n"
"\n"
"QHeaderView::section{\n"
"        background-color:#55aaff;\n"
"        padding:2px;\n"
"        border:1px solid #fffff8;\n"
"        font-size:12pt;\n"
"        \n"
"}\n"
"QTableWidget{\n"
"        gridline-color: #000000;\n"
"        font-size:12pt;\n"
"}\n"
"QTableWidget QTableCornerButton:section{\n"
"        background-color:#55aaff;\n"
"        border:1px solid #ffffff;\n"
"}\n"
"\n"
"")
        self.TablaAct.setObjectName("TablaAct")
        self.TablaAct.setColumnCount(7)
        self.TablaAct.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAct.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAct.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAct.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAct.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAct.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAct.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.TablaAct.setHorizontalHeaderItem(6, item)
        self.verticalLayout_2.addWidget(self.TablaAct)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_13 = QtWidgets.QLabel(self.widget1)
        self.label_13.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 87 13pt \"Arial Black\";\n"
"")
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_11.addWidget(self.label_13)
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem19)
        self.verticalLayout_2.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.label_15 = QtWidgets.QLabel(self.widget1)
        self.label_15.setMinimumSize(QtCore.QSize(30, 25))
        self.label_15.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 0, 0, 1, 1)
        self.ActNombres = QtWidgets.QLineEdit(self.widget1)
        self.ActNombres.setMinimumSize(QtCore.QSize(174, 25))
        self.ActNombres.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"font: 12pt \"Arial\";\n"
"border: none;\n"
"\n"
"border-bottom: 1px solid black;")
        self.ActNombres.setObjectName("ActNombres")
        self.gridLayout_5.addWidget(self.ActNombres, 0, 1, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget1)
        self.label_16.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 0, 2, 1, 1)
        self.ActApellidos = QtWidgets.QLineEdit(self.widget1)
        self.ActApellidos.setMinimumSize(QtCore.QSize(174, 21))
        self.ActApellidos.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 12pt \"Arial\";\n"
"border-bottom: 1px solid black;")
        self.ActApellidos.setObjectName("ActApellidos")
        self.gridLayout_5.addWidget(self.ActApellidos, 0, 3, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget1)
        self.label_17.setMinimumSize(QtCore.QSize(30, 25))
        self.label_17.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_17.setObjectName("label_17")
        self.gridLayout_5.addWidget(self.label_17, 1, 0, 1, 1)
        self.Actidd = QtWidgets.QLineEdit(self.widget1)
        self.Actidd.setMinimumSize(QtCore.QSize(174, 25))
        self.Actidd.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 12pt \"Segoe MDL2 Assets\";\n"
"border-bottom: 1px solid black;")
        self.Actidd.setObjectName("Actidd")
        self.gridLayout_5.addWidget(self.Actidd, 1, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.widget1)
        self.label_18.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_18.setObjectName("label_18")
        self.gridLayout_5.addWidget(self.label_18, 1, 2, 1, 1)
        self.ActComboSex = QtWidgets.QComboBox(self.widget1)
        self.ActComboSex.setMinimumSize(QtCore.QSize(174, 21))
        self.ActComboSex.setStyleSheet("\n"
"border: none;\n"
"font: 12pt \"Arial\";\n"
"border-bottom: 1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.ActComboSex.setObjectName("ActComboSex")
        self.ActComboSex.addItem("")
        self.ActComboSex.addItem("")
        self.ActComboSex.addItem("")
        self.gridLayout_5.addWidget(self.ActComboSex, 1, 3, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.widget1)
        self.label_19.setMinimumSize(QtCore.QSize(30, 25))
        self.label_19.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_19.setObjectName("label_19")
        self.gridLayout_5.addWidget(self.label_19, 2, 0, 1, 1)
        self.ActCombTipo = QtWidgets.QComboBox(self.widget1)
        self.ActCombTipo.setMinimumSize(QtCore.QSize(174, 25))
        self.ActCombTipo.setStyleSheet("\n"
"border: none;\n"
"font:12pt \"Arial\";\n"
"border-bottom: 1px solid black;\n"
"background-color: rgb(255, 255, 255);\n"
"")
        self.ActCombTipo.setObjectName("ActCombTipo")
        self.ActCombTipo.addItem("")
        self.ActCombTipo.addItem("")
        self.ActCombTipo.addItem("")
        self.gridLayout_5.addWidget(self.ActCombTipo, 2, 1, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.widget1)
        self.label_20.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"\n"
"")
        self.label_20.setObjectName("label_20")
        self.gridLayout_5.addWidget(self.label_20, 2, 2, 1, 1)
        self.ActNiden = QtWidgets.QLineEdit(self.widget1)
        self.ActNiden.setMinimumSize(QtCore.QSize(174, 21))
        self.ActNiden.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border: none;\n"
"font: 12pt \"Arial\";\n"
"border-bottom: 1px solid black;")
        self.ActNiden.setObjectName("ActNiden")
        self.gridLayout_5.addWidget(self.ActNiden, 2, 3, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.widget1)
        self.label_25.setObjectName("label_25")
        self.gridLayout_5.addWidget(self.label_25, 3, 2, 1, 1)
        self.ActFecNac = QtWidgets.QLineEdit(self.widget1)
        self.ActFecNac.setMinimumSize(QtCore.QSize(174, 21))
        self.ActFecNac.setStyleSheet("background-color: rgba(0, 0, 0,0%);\n"
"border: none;\n"
"font: 12pt \"Segoe MDL2 Assets\";\n"
"border-bottom: 1px solid black;")
        self.ActFecNac.setObjectName("ActFecNac")
        self.gridLayout_5.addWidget(self.ActFecNac, 3, 3, 1, 1)
        self.horizontalLayout_21.addLayout(self.gridLayout_5)
        self.ActCalen = QtWidgets.QCalendarWidget(self.widget1)
        self.ActCalen.setStyleSheet("background-color: rgb(221, 225, 255);\n"
"color: rgb(0, 0, 0);\n"
"")
        self.ActCalen.setObjectName("ActCalen")
        self.horizontalLayout_21.addWidget(self.ActCalen)
        self.verticalLayout_2.addLayout(self.horizontalLayout_21)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.ActRegresar = QtWidgets.QPushButton(self.widget1)
        self.ActRegresar.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.ActRegresar.setObjectName("ActRegresar")
        self.horizontalLayout_22.addWidget(self.ActRegresar)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem20)
        self.ActBoton = QtWidgets.QPushButton(self.widget1)
        self.ActBoton.setStyleSheet("QPushButton{\n"
"    \n"
"    background-color: rgb(0, 0, 0);\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(255, 255, 255);\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"\n"
"    background-color:#00aaff;\n"
"    font: 87 13pt \"Arial Black\";\n"
"    color: rgb(0, 0, 0);\n"
"\n"
"}")
        self.ActBoton.setObjectName("ActBoton")
        self.horizontalLayout_22.addWidget(self.ActBoton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_22)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/cct/imagenes/klipartz.com (16).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.widget1, icon4, "")
        self.gridLayout_4.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)

        self.mydb = mysql.connector.connect(host="localhost", user="root", password="", database='estudiantes')
        self.mycursor = self.mydb.cursor()
        self.datosTotal = Metodos()
        self.Registrar.clicked.connect(self.insertarEstudiante)
        self.Refrescar.clicked.connect(self.mostrarDatos)
        self.ConBoton.clicked.connect(self.FiltrarConsulta)
        self.ReRegresar.clicked.connect(self.VolverLogin)
        self.ConRegresar.clicked.connect(self.VolverLogin)
        self.EliBotonRegre.clicked.connect(self.VolverLogin)
        self.ActRegresar.clicked.connect(self.VolverLogin)
        self.RegresarBase.clicked.connect(self.VolverLogin)
        self.EliBotonConsu.clicked.connect(self.FiltrarConsultaEli)
        self.EliBoton.clicked.connect(self.EliminarEstudiante)
        self.ActBotonFiltrar.clicked.connect(self.FiltrarActualiza)
        self.mostrarDatosEli()
        self.mostrarDatosIngreso()
        self.mostrarDatos()
        self.mostrarDatosActu()
        self.mostrarDatosConsulta()
        self.ActBoton.clicked.connect(self.ActEstudiante)

        self.TablaAct.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.TablaAct.cellClicked.connect(self.funcionalclickearceldas)


        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Estudiantes"))
        item = self.TablaEstudiante.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.TablaEstudiante.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombres"))
        item = self.TablaEstudiante.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellidos"))
        item = self.TablaEstudiante.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tipo"))
        item = self.TablaEstudiante.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cédula"))
        item = self.TablaEstudiante.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fecha Nacimiento"))
        item = self.TablaEstudiante.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Género"))
        self.RegresarBase.setText(_translate("MainWindow", "Cerrar sesión"))
        self.Refrescar.setText(_translate("MainWindow", "Refrescar"))
        self.label_2.setText(_translate("MainWindow", "Añadir Estudiantes"))
        item = self.TablaInsertar.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.TablaInsertar.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombres"))
        item = self.TablaInsertar.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellidos"))
        item = self.TablaInsertar.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tipo"))
        item = self.TablaInsertar.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cédula"))
        item = self.TablaInsertar.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fecha Nacimiento"))
        item = self.TablaInsertar.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Género"))
        self.label_6.setText(_translate("MainWindow", "Datos  Estudiante"))
        self.label_7.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (10).png\"/></p></body></html>"))
        self.ReNombres.setPlaceholderText(_translate("MainWindow", "Nombres"))
        self.label_9.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (10).png\"/></p></body></html>"))
        self.ReApellidos.setPlaceholderText(_translate("MainWindow", "Apellidos"))
        self.label_10.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (11).png\"/></p></body></html>"))
        self.Reidd.setPlaceholderText(_translate("MainWindow", "Id"))
        self.label_8.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (9).png\"/></p></body></html>"))
        self.ReComboSex.setItemText(0, _translate("MainWindow", "Sexo"))
        self.ReComboSex.setItemText(1, _translate("MainWindow", "Masculino"))
        self.ReComboSex.setItemText(2, _translate("MainWindow", "Femenino"))
        self.label_12.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (13).png\"/></p></body></html>"))
        self.ReComboTipo.setItemText(0, _translate("MainWindow", "Tipo de identificación"))
        self.ReComboTipo.setItemText(1, _translate("MainWindow", "Tarjeta de identidad"))
        self.ReComboTipo.setItemText(2, _translate("MainWindow", "Cédula"))
        self.label_11.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (13).png\"/></p></body></html>"))
        self.ReNiden.setPlaceholderText(_translate("MainWindow", "Numero Identificación"))
        self.label_24.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (20).png\"/></p></body></html>"))
        self.ReFecNac.setPlaceholderText(_translate("MainWindow", "Fecha Nacimiento"))
        self.ReRegresar.setText(_translate("MainWindow", "Cerrar sesión"))
        self.Registrar.setText(_translate("MainWindow", "Registrar"))
        self.label_3.setText(_translate("MainWindow", "Eliminar Estudiantes"))
        self.label_22.setText(_translate("MainWindow", "Filtro para consultar:"))
        self.EliComboConsu.setItemText(0, _translate("MainWindow", "Id"))
        self.EliComboConsu.setItemText(1, _translate("MainWindow", "Nombre"))
        self.EliComboConsu.setItemText(2, _translate("MainWindow", "Apellido"))
        self.EliComboConsu.setItemText(3, _translate("MainWindow", "Cedula"))
        self.EliComboConsu.setItemText(4, _translate("MainWindow", "FechaNac"))
        self.EliConTex.setPlaceholderText(_translate("MainWindow", "Busquedá"))
        self.EliBotonConsu.setText(_translate("MainWindow", "Consultar"))
        self.label_23.setText(_translate("MainWindow", "Filtro para eliminar:"))
        self.EliCombo.setItemText(0, _translate("MainWindow", "Id"))
        self.EliCombo.setItemText(1, _translate("MainWindow", "Nombre"))
        self.EliCombo.setItemText(2, _translate("MainWindow", "Apellido"))
        self.EliCombo.setItemText(3, _translate("MainWindow", "Cedula"))
        self.EliCombo.setItemText(4, _translate("MainWindow", "FechaNac"))
        self.EliTex.setPlaceholderText(_translate("MainWindow", "Eliminar"))
        self.EliBoton.setText(_translate("MainWindow", "Eliminar"))
        item = self.TablaEli.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.TablaEli.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombres"))
        item = self.TablaEli.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellidos"))
        item = self.TablaEli.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tipo"))
        item = self.TablaEli.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cédula"))
        item = self.TablaEli.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fecha Nacimiento"))
        item = self.TablaEli.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Género"))
        self.EliBotonRegre.setText(_translate("MainWindow", "Cerrar sesión"))
        self.label_4.setText(_translate("MainWindow", "Consultar Estudiantes"))
        self.label_21.setText(_translate("MainWindow", "Filtro para consultar"))
        self.ConCombo.setItemText(0, _translate("MainWindow", "id"))
        self.ConCombo.setItemText(1, _translate("MainWindow", "Nombre"))
        self.ConCombo.setItemText(2, _translate("MainWindow", "Apellido"))
        self.ConCombo.setItemText(3, _translate("MainWindow", "Cedula"))
        self.ConCombo.setItemText(4, _translate("MainWindow", "FechaNac"))
        self.ConTex.setPlaceholderText(_translate("MainWindow", "Busquedá"))
        self.ConBoton.setText(_translate("MainWindow", "Consultar"))
        item = self.TablaCon.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.TablaCon.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombres"))
        item = self.TablaCon.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellidos"))
        item = self.TablaCon.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tipo"))
        item = self.TablaCon.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cédula"))
        item = self.TablaCon.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fecha Nacimiento"))
        item = self.TablaCon.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Género"))
        self.ConRegresar.setText(_translate("MainWindow", "Cerrar sesión"))
        self.label_5.setText(_translate("MainWindow", "Actualizar Estudiantes"))
        self.label_14.setText(_translate("MainWindow", "Filtro para actualizar"))
        self.ActCombo.setItemText(0, _translate("MainWindow", "id"))
        self.ActCombo.setItemText(1, _translate("MainWindow", "Nombre"))
        self.ActCombo.setItemText(2, _translate("MainWindow", "Apellido"))
        self.ActCombo.setItemText(3, _translate("MainWindow", "Cedula"))
        self.ActCombo.setItemText(4, _translate("MainWindow", "FechaNac"))
        self.ActTex.setPlaceholderText(_translate("MainWindow", "Busquedá"))
        self.ActBotonFiltrar.setText(_translate("MainWindow", "Filtrar"))
        item = self.TablaAct.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Id"))
        item = self.TablaAct.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Nombres"))
        item = self.TablaAct.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Apellidos"))
        item = self.TablaAct.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Tipo"))
        item = self.TablaAct.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Cédula"))
        item = self.TablaAct.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Fecha Nacimiento"))
        item = self.TablaAct.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Género"))
        self.label_13.setText(_translate("MainWindow", "Datos  Estudiante"))
        self.label_15.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (10).png\"/></p></body></html>"))
        self.ActNombres.setPlaceholderText(_translate("MainWindow", "Nombres"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (10).png\"/></p></body></html>"))
        self.ActApellidos.setPlaceholderText(_translate("MainWindow", "Apellidos"))
        self.label_17.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (11).png\"/></p></body></html>"))
        self.Actidd.setPlaceholderText(_translate("MainWindow", "Id"))
        self.label_18.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (9).png\"/></p></body></html>"))
        self.ActComboSex.setItemText(0, _translate("MainWindow", "Sexo"))
        self.ActComboSex.setItemText(1, _translate("MainWindow", "Masculino"))
        self.ActComboSex.setItemText(2, _translate("MainWindow", "Femenino"))
        self.label_19.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (13).png\"/></p></body></html>"))
        self.ActCombTipo.setItemText(0, _translate("MainWindow", "Tipo de identificación"))
        self.ActCombTipo.setItemText(1, _translate("MainWindow", "Tarjeta de identidad"))
        self.ActCombTipo.setItemText(2, _translate("MainWindow", "Cédula"))
        self.label_20.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (13).png\"/></p></body></html>"))
        self.ActNiden.setPlaceholderText(_translate("MainWindow", "Numero Identificación"))
        self.label_25.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/cct/imagenes/klipartz.com (20).png\"/></p></body></html>"))
        self.ActFecNac.setPlaceholderText(_translate("MainWindow", "Fecha Nacimiento"))
        self.ActRegresar.setText(_translate("MainWindow", "Cerrar sesión"))
        self.ActBoton.setText(_translate("MainWindow", "Actualizar"))

        self.TablaCon.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.TablaInsertar.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.TablaEstudiante.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.TablaEli.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.TablaAct.setEditTriggers(QtWidgets.QTableWidget.NoEditTriggers)
        self.ReCalen.selectionChanged.connect(self.cambioCalen)
        self.ActCalen.selectionChanged.connect(self.cambioCalenAct)
    def cambioCalen(self):
        self.fecha = self.ReCalen.selectedDate()

        self.ReFecNac.setText(str(self.fecha.toPyDate()))

    def cambioCalenAct(self):
            self.fecha = self.ActCalen.selectedDate()

            self.ActFecNac.setText(str(self.fecha.toPyDate()))
    def funcionalclickearceldas(self):
       nombre0=self.TablaAct.selectedIndexes()[0].data()
       self.Actidd.setText(str(nombre0))
       nombre1 = self.TablaAct.selectedIndexes()[1].data()
       self.ActNombres.setText(str(nombre1))
       nombre2 = self.TablaAct.selectedIndexes()[2].data()
       self.ActApellidos.setText(str(nombre2))
       nombre4 = self.TablaAct.selectedIndexes()[3].data()
       self.ActCombTipo.setCurrentText(str(nombre4))
       nombre3 = self.TablaAct.selectedIndexes()[4].data()
       self.ActNiden.setText(str(nombre3))
       nombre5 = self.TablaAct.selectedIndexes()[5].data()
       self.ActFecNac.setText(str(nombre5))
       nombre6 = self.TablaAct.selectedIndexes()[6].data()
       self.ActComboSex.setCurrentText(str(nombre6))





    def mostrarDatos(self):
        info=self.datosTotal.BuscarEstudiante()
        i = len(info)
        self.TablaEstudiante.setRowCount(i)
        tablerow=0
        for fila in info:
            self.TablaEstudiante.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(fila[0]))
            self.TablaEstudiante.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(fila[1]))
            self.TablaEstudiante.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(fila[2]))
            self.TablaEstudiante.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(fila[3]))
            self.TablaEstudiante.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(fila[4]))
            self.TablaEstudiante.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(fila[5]))
            self.TablaEstudiante.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(fila[6]))
            tablerow += 1
    def mostrarDatosIngreso(self):
        info=self.datosTotal.BuscarEstudiante()
        i = len(info)
        self.TablaInsertar.setRowCount(i)
        tablerow=0
        for fila in info:
            self.TablaInsertar.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(fila[0]))
            self.TablaInsertar.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(fila[1]))
            self.TablaInsertar.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(fila[2]))
            self.TablaInsertar.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(fila[3]))
            self.TablaInsertar.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(fila[4]))
            self.TablaInsertar.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(fila[5]))
            self.TablaInsertar.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(fila[6]))
            tablerow += 1
    def mostrarDatosConsulta(self):
        infora=self.datosTotal.BuscarEstudiante()
        i = len(infora)
        self.TablaCon.setRowCount(i)
        tablerow = 0
        for fila in infora:
            self.TablaCon.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(fila[0]))
            self.TablaCon.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(fila[1]))
            self.TablaCon.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(fila[2]))
            self.TablaCon.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(fila[3]))
            self.TablaCon.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(fila[4]))
            self.TablaCon.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(fila[5]))
            self.TablaCon.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(fila[6]))
            tablerow += 1

    def mostrarDatosActu(self):
        infora = self.datosTotal.BuscarEstudiante()
        i = len(infora)
        self.TablaAct.setRowCount(i)
        tablerow = 0
        for fila in infora:
            self.TablaAct.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(fila[0]))
            self.TablaAct.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(fila[1]))
            self.TablaAct.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(fila[2]))
            self.TablaAct.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(fila[3]))
            self.TablaAct.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(fila[4]))
            self.TablaAct.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(fila[5]))
            self.TablaAct.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(fila[6]))
            tablerow += 1
    def FiltrarConsulta(self):

        filtro=self.ConCombo.currentText()
        filtro=str(""+filtro+"")
        parametro=self.ConTex.text()
        parametro=("'"+parametro+"'")
        infor= self.datosTotal.FiltroEstudiante(filtro,parametro)
        i=len(infor)
        self.TablaCon.setRowCount(i)
        tablerow = 0
        for fila in infor:
                self.TablaCon.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(fila[0]))
                self.TablaCon.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(fila[1]))
                self.TablaCon.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(fila[2]))
                self.TablaCon.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(fila[3]))
                self.TablaCon.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(fila[4]))
                self.TablaCon.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(fila[5]))
                self.TablaCon.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(fila[6]))
                tablerow += 1

        self.ConTex.clear()
    def mostrarDatosEli(self):

        dat=self.datosTotal.BuscarEstudiante()
        i=len(dat)
        self.TablaEli.setRowCount(i)
        tablerow=0
        for fila in dat:
            self.TablaEli.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(fila[0]))
            self.TablaEli.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(fila[1]))
            self.TablaEli.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(fila[2]))
            self.TablaEli.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(fila[3]))
            self.TablaEli.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(fila[4]))
            self.TablaEli.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(fila[5]))
            self.TablaEli.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(fila[6]))
            tablerow += 1


    def FiltrarConsultaEli(self):
        fil = self.EliComboConsu.currentText()
        fil = str("" + fil + "")
        para = self.EliConTex.text()
        para= ("'" + para + "'")
        infor = self.datosTotal.FiltroEstudiante(fil, para)
        i = len(infor)
        self.TablaEli.setRowCount(i)
        tablerow = 0
        for fila in infor:
            self.TablaEli.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(fila[0]))
            self.TablaEli.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(fila[1]))
            self.TablaEli.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(fila[2]))
            self.TablaEli.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(fila[3]))
            self.TablaEli.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(fila[4]))
            self.TablaEli.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(fila[5]))
            self.TablaEli.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(fila[6]))
            tablerow += 1
            self.EliConTex.clear()
    def FiltrarActualiza(self):
        filtro=self.ActCombo.currentText()
        filtro=str(""+filtro+"")
        parametro=self.ActTex.text()
        parametro=str("'"+parametro+"'")
        infor= self.datosTotal.FiltroEstudiante(filtro,parametro)
        i=len(infor)
        self.TablaAct.setRowCount(i)
        tablerow = 0
        for fila in infor:
            self.TablaAct.setItem(tablerow, 0, QtWidgets.QTableWidgetItem(fila[0]))
            self.TablaAct.setItem(tablerow, 1, QtWidgets.QTableWidgetItem(fila[1]))
            self.TablaAct.setItem(tablerow, 2, QtWidgets.QTableWidgetItem(fila[2]))
            self.TablaAct.setItem(tablerow, 3, QtWidgets.QTableWidgetItem(fila[3]))
            self.TablaAct.setItem(tablerow, 4, QtWidgets.QTableWidgetItem(fila[4]))
            self.TablaAct.setItem(tablerow, 5, QtWidgets.QTableWidgetItem(fila[5]))
            self.TablaAct.setItem(tablerow, 6, QtWidgets.QTableWidgetItem(fila[6]))
            tablerow += 1

        self.ActTex.clear()
    def insertarEstudiante(self):
            confirmar = QtWidgets.QMessageBox()
            confirmar.setIcon(confirmar.Question)
            confirmar.setText("¿Realmente desea añadir este usuario?")
            confirmar.setStandardButtons(confirmar.Yes | confirmar.No | confirmar.Cancel)
            op = confirmar.exec()

            if op == 16384:
                if not self.ReNombres.text()  or not  self.ReApellidos.text() or not self.ReNiden.text() or not  self.Reidd.text() or not self.ReFecNac.text():
                        confirmar = QtWidgets.QMessageBox()
                        confirmar.setIcon(confirmar.Warning)
                        confirmar.setText("¡Hay campos vacíos!")
                        confirmar.exec_()
                else:
                        if self.ReComboTipo.currentText() == "Tipo de identificación":
                                confirmar = QtWidgets.QMessageBox()
                                confirmar.setIcon(confirmar.Warning)
                                confirmar.setText("!Seleccione algún tipo de identificación¡")
                                confirmar.exec_()
                        elif self.ReComboSex.currentText() == "Sexo":
                                confirmar = QtWidgets.QMessageBox()
                                confirmar.setIcon(confirmar.Warning)
                                confirmar.setText("Seleccione algún tipo de género ")
                                confirmar.exec_()
                        else:
                                name = self.ReNombres.text()
                                apelli = self.ReApellidos.text()
                                sex = self.ReComboSex.currentText()
                                numide = self.ReNiden.text()
                                numI = ("'" + numide + "'")
                                fechaNac = self.ReFecNac.text()
                                iden = self.ReComboTipo.currentText()
                                id = self.Reidd.text()
                                aidi = ("'" + id + "'")
                                self.datosTotal.AgregrarEstudiante(id, name, apelli, iden, numide, fechaNac, sex)
                                self.mostrarDatosIngreso()
                                self.mostrarDatosEli()
                                self.mostrarDatos()
                                self.mostrarDatosActu()
                                self.mostrarDatosConsulta()
                                self.ReNombres.clear()
                                self.ReApellidos.clear()
                                self.Reidd.clear()
                                self.ReNiden.clear()
                                self.ReFecNac.clear()
                                self.ReComboSex.setCurrentIndex(0)
                                self.ReComboTipo.setCurrentIndex(0)

            elif op == 65536:
                    confirmar = QtWidgets.QMessageBox()
                    confirmar.setIcon(confirmar.Warning)
                    confirmar.setText("No se agrego el usuario")
                    confirmar.exec_()
            elif op == 4194304:
                    confirmar = QtWidgets.QMessageBox()
                    confirmar.setIcon(confirmar.Warning)
                    confirmar.setText("Se cancelo")
                    confirmar.exec_()


    def EliminarEstudiante(self):
        confirmar= QtWidgets.QMessageBox()
        confirmar.setIcon(confirmar.Question)
        confirmar.setText("¿Realmente desea eliminar este usuario?")
        confirmar.setStandardButtons(confirmar.Yes|confirmar.No|confirmar.Cancel)
        op= confirmar.exec()
        if op==16384:

                if not self.EliTex.text():
                        confirmar = QtWidgets.QMessageBox()
                        confirmar.setIcon(confirmar.Warning)
                        confirmar.setText("El campo para eliminar esta vacío")
                        confirmar.exec_()
                else:
                        filt=self.EliCombo.currentText()
                        filt=str(""+filt+"")
                        parametr=self.EliTex.text()
                        parametr=str("'"+parametr+"'")
                        datosB=(self.datosTotal.EliminaEstudiante(filt,parametr))
                        self.mostrarDatosEli()
                        self.mostrarDatosIngreso()
                        self.mostrarDatos()
                        self.mostrarDatosActu()
                        self.mostrarDatosConsulta()
                        if datosB==0:
                                confirmar = QtWidgets.QMessageBox()
                                confirmar.setIcon(confirmar.Warning)
                                confirmar.setText("Este usuario no esta registrado")
                                confirmar.exec_()
                        else:
                                confirmar = QtWidgets.QMessageBox()
                                confirmar.setIcon(confirmar.Warning)
                                confirmar.setText("Se elimino el usuario ")
                                confirmar.exec_()
        elif op==65536:
                confirmar = QtWidgets.QMessageBox()
                confirmar.setIcon(confirmar.Warning)
                confirmar.setText("No se elimino")
                confirmar.exec_()
        elif op==4194304:
                confirmar = QtWidgets.QMessageBox()
                confirmar.setIcon(confirmar.Warning)
                confirmar.setText("Se cancelo")
                confirmar.exec_()



    def ActEstudiante(self):
        confirmar = QtWidgets.QMessageBox()
        confirmar.setIcon(confirmar.Question)
        confirmar.setText("¿Realmente desea actualizar este usuario?")
        confirmar.setStandardButtons(confirmar.Yes | confirmar.No | confirmar.Cancel)
        op = confirmar.exec()
        if op == 16384:
                if not self.ActNombres.text() or not self.ActApellidos.text() or not self.ActNiden.text() or not self.Actidd.text() or not self.ActFecNac.text():
                        confirmar = QtWidgets.QMessageBox()
                        confirmar.setIcon(confirmar.Warning)
                        confirmar.setText("¡Hay campos vacíos!")
                        confirmar.exec_()
                else:
                        if self.ActCombTipo.currentText() == "Tipo de identificación":
                                confirmar = QtWidgets.QMessageBox()
                                confirmar.setIcon(confirmar.Warning)
                                confirmar.setText("!Seleccione algún tipo de identificación¡")
                                confirmar.exec_()
                        elif self.ActComboSex.currentText() == "Sexo":
                                confirmar = QtWidgets.QMessageBox()
                                confirmar.setIcon(confirmar.Warning)
                                confirmar.setText("Seleccione algún tipo de género ")
                                confirmar.exec_()
                        else:
                                name = self.ActNombres.text()
                                apelli = self.ActApellidos.text()
                                sex = self.ActComboSex.currentText()
                                numide = self.ActNiden.text()
                                fechaNac = self.ActFecNac.text()
                                iden = self.ActCombTipo.currentText()
                                id = self.Actidd.text()
                                self.datosTotal.ActualizarEstudiante(name, apelli, iden, numide, fechaNac, sex,id)
                                self.mostrarDatosActu()
                                self.mostrarDatosEli()
                                self.mostrarDatosIngreso()
                                self.mostrarDatos()
                                self.mostrarDatosConsulta()
                                self.ActNombres.clear()
                                self.ActApellidos.clear()
                                self.Actidd.clear()
                                self.ActNiden.clear()
                                self.ActFecNac.clear()
                                self.ActComboSex.setCurrentIndex(0)
                                self.ActCombTipo.setCurrentIndex(0)
                                confirmar = QtWidgets.QMessageBox()
                                confirmar.setIcon(confirmar.Warning)
                                confirmar.setText("Se actualizo con exito el usuario")
                                confirmar.exec_()
        elif op==65536:
                confirmar = QtWidgets.QMessageBox()
                confirmar.setIcon(confirmar.Warning)
                confirmar.setText("No se actualizo")
                confirmar.exec_()
        elif op==4194304:
                confirmar = QtWidgets.QMessageBox()
                confirmar.setIcon(confirmar.Warning)
                confirmar.setText("Se cancelo")
                confirmar.exec_()
    def VolverLogin(self):
        self.ventana = QtWidgets.QMainWindow()
        self.cru = InIngreso2.Ui_MainWiningreso()
        self.cru.setupUi(self.ventana)
        self.ventana.show()
        MainWindow.hide()


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindowGestionar()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
